# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: LICENSES/headers
    - id: check-added-large-files

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: [--enable=unused-import --max-line-length=80, --disable=all]


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: insert-license
        name: insert MIT license
        exclude: ^(docs/source)
        files: \.py$
        args:
          - --license-filepath
          - LICENSES/headers/MIT-Clause.txt
